export const ADD_INCREMENT_REQUEST = 'ADD_INCREMENT_REQUEST';
export const ADD_INCREMENT_SUCCESS = 'ADD_INCREMENT_SUCCESS';
export const ADD_INCREMENT_ERROR = 'ADD_INCREMENT_ERROR';

export const ADD_DECREMENT_REQUEST = 'ADD_DECREMENT_REQUEST';
export const ADD_DECREMENT_SUCCESS = 'ADD_DECREMENT_SUCCESS';
export const ADD_DECREMENT_ERROR = 'ADD_DECREMENT_ERROR';

export const ADD_FAKEAPI_REQUEST = 'ADD_FAKEAPI_REQUEST';
export const ADD_FAKEAPI_SUCCESS = 'ADD_FAKEAPI_SUCCESS';
export const ADD_FAKEAPI_ERROR = 'ADD_FAKEAPI_ERROR';

export const ADD_ADD_TO_CART_SUCCESS = 'ADD_ADD_TO_CART_SUCCESS';